"""empty message

Revision ID: 656a0fa13557
Revises: cbd845a10987
Create Date: 2026-03-07 16:38:24.421977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656a0fa13557'
down_revision: Union[str, Sequence[str], None] = 'cbd845a10987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailinglist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.alter_column('businesses', 'ai_credits',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_products_image_embedding'), table_name='products', postgresql_ops={'image_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_products_image_embedding'), 'products', ['image_embedding'], unique=False, postgresql_ops={'image_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('businesses', 'ai_credits',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_table('mailinglist')
    # ### end Alembic commands ###
