"""Add is_active column to products

Revision ID: cbd845a10987
Revises: d6e5f539f0c3
Create Date: 2026-02-23 09:58:54.336575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd845a10987'
down_revision: Union[str, Sequence[str], None] = 'd6e5f539f0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
