"""Add reference in orders

Revision ID: dc5211b04f0a
Revises: 1d625794c910
Create Date: 2026-03-11 01:42:31.842679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5211b04f0a'
down_revision: Union[str, Sequence[str], None] = '1d625794c910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reference', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'reference')
    # ### end Alembic commands ###
