"""Added password field to userdb

Revision ID: 3d8b3a1dc015
Revises: 3ddbd3915b6e
Create Date: 2025-12-31 00:10:29.403855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8b3a1dc015'
down_revision = '3ddbd3915b6e'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as nullable
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(
            sa.Column('password_hash', sa.String(length=255), nullable=True)
        )

    # 2. Backfill existing users with a placeholder hash
    op.execute(
        "UPDATE users SET password_hash = 'TEMP_PASSWORD_RESET_REQUIRED'"
    )

    # 3. Enforce NOT NULL
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'password_hash',
            nullable=False
        )



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
