"""User and Message tables

Revision ID: 3ddbd3915b6e
Revises: 
Create Date: 2025-12-30 16:01:58.948783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddbd3915b6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the table completely to avoid column alteration conflicts
    op.drop_table('messages')
    
    # Recreate the table with the correct new schema
    op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('sender', sa.String(length=10), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_response', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('messages_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('sender')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
