"""User and Message tables

Revision ID: 3ddbd3915b6e
Revises: 
Create Date: 2025-12-30 16:01:58.948783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddbd3915b6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear existing data to prevent NotNullViolation when adding 'sender' column
    op.execute("DELETE FROM messages")

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sender', sa.String(length=10), nullable=False))
        batch_op.drop_constraint(batch_op.f('messages_user_id_key'), type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_message')
        batch_op.drop_column('bot_response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_response', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('messages_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('sender')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
