"""AI Persona

Revision ID: 636c5198400e
Revises: dfe5ea1c0312
Create Date: 2026-02-09 11:06:36.244257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636c5198400e'
down_revision = 'dfe5ea1c0312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('persona')

    # ### end Alembic commands ###
