"""Add phone_number_id to Business

Revision ID: a89325500b19
Revises: e7e5163c2a50
Create Date: 2026-02-07 00:17:13.914158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89325500b19'
down_revision = 'e7e5163c2a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['phone_number_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_number_id')

    # ### end Alembic commands ###
